# Generated by Django 4.2.4 on 2023-08-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveArticulo', models.CharField(max_length=50)),
                ('descripcionArticulo', models.CharField(max_length=50)),
                ('numExistencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=50)),
                ('apellidosCliente', models.CharField(max_length=50)),
                ('correoCliente', models.CharField(max_length=50)),
                ('adeuda', models.BooleanField()),
            ],
        ),
    ]
